name: ChristmasMiracle
version: 1.0.1-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.com.gmail.gogobebe2.christmasmiracle
description: Allows creation of everlasting snow.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  snow:
permissions:
  snow.*:
    default: op